# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Prova CI con Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs_on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java_version: 11
    - name: Run test with Maven
      run: mvn -B clean test
  
  
  build:

    runs_on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java_version: 11
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - name: Upload jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: target/162967_SimoneCassetta_Homework_Qualita-1.0-SNAPSHOT.jar
      
